### ISSUE TITLE
Downloads larger than 2GB fail from within QGIS

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#442]
When downloading results within the toolbox, QGIS apparently caps the file size at 2GB causing the client to download an incomplete NetCDF in the case that it is bigger than that.

The error that a client receives is cryptical, it complains that the results that are loaded in are too old for the current plugin version. (See topdesk 1910 0042)

Please add a warning in the download screen that NetCDF's can only be max 2GB and give a warning to the user when attempting to download a NetCDF larger than 2GB, and in a pop up mention this:

The results you are trying to download exceed the download limitations of QGIS. Please download the NetCDF via the email you have received to bypass the QGIS limitations. Did you not receive an email? Then contact our servicedesk: servicedesk@nelen-schuurmans.nl

**Comment by Jonasvsl** [comment]
obsolete, lizard dependency will be removed and downloads is solved with API QGIS client

**Comment by leendertvanwolfswinkel** [comment]
issue is still relevant for downloading results > 7 days old (tested with QGIS 3.16.4, 3Di Toolbox 1.19)

**Comment by Jonasvsl** [comment]
@leendertvanwolfswinkel relevant for when downloading from lizard you mean?
